### ISSUE TITLE
Can you include a binary for us to download?

### ISSUE THREAD

**Issue by CaffGeek** [manutalcual/winredock#1]
I don't have the tools to build it on my windows machine.

**Comment by manutalcual** [comment]
I've already submitted a binary.
I've found some non important glitches and I'm working on that.
I've found to best use this tool is to click on the desktop view corner and then the app icon: this will move and size all windows.

If you find something failing, just create another issue and I will solve it as best as I can.

Thanks for trying the app!

**Comment by manutalcual** [comment]
Hi!
I've added the binary:
https://github.com/manutalcual/winredock/tree/master/bin
I've detected some glitches, although not very importants.

Kind regards,
Manu

**Comment by CaffGeek** [comment]
Doesn't run, complains about a few missing dlls, for example, this one
![image](https://user-images.githubusercontent.com/2037167/46742993-c1d0fa80-cc6d-11e8-964f-f57eecb647d3.png)

**Comment by CaffGeek** [comment]
I'm thinking I might need to install cygwin?
![image](https://user-images.githubusercontent.com/2037167/46743566-fa250880-cc6e-11e8-9519-2d405bb940e8.png)

**Comment by manutalcual** [comment]
Which windows version are you using?

**Comment by manutalcual** [comment]
I'm installing VS community edition to compile from Windows and avoid Cygwin.
It may take a while. I will comment here when it is ready, but we could follow with the Cygwin dll problem just in case other people find the same problem.

**Comment by CaffGeek** [comment]
Win 10 Pro, Version 1709 - Build 16299.192

**Comment by manutalcual** [comment]
Check the size of the DLLs. May be your antivirus or Windows defender is banning downloaded DLLs.

**Comment by CaffGeek** [comment]
That could be it, they're all 52kb. Can you zip it up for d/l?

**Comment by manutalcual** [comment]
Done. Try them and tell me of it works.

**Comment by CaffGeek** [comment]
Binary works now, but it's making a total mess of the windows. Could be partly that I'm dual screen, with different resolutions, and have my displays stacked vertically, not horizontally?

**Comment by manutalcual** [comment]
I have three monitors, same resolution, several configurations: windowed, maximized, fullscreen, etc.
Have you run `Get windows` menu and `Save config`?

**Comment by CaffGeek** [comment]
Yep, ran in the following order
1. Get windows
2. Save Config
3. Read Config
left click on icon.

...windows got all resized (most to insanely tiny sizes) and put all over the place.

**Comment by manutalcual** [comment]
Weird. Can you send me the window_list.json file that gets generated in the same dir as binary?

**Comment by manutalcual** [comment]
I close this issue because I don't have any response after several days.
