### ISSUE TITLE
Executable please?

### ISSUE THREAD

**Issue by Ardrikk** [manutalcual/winredock#17]
I would love to use this; could I please have an executable that I can run?  I don't know how to compile what you have to make it work.

**Comment by Ardrikk** [comment]
Actually, I think I have it "installed" already thanks to downloading the zip file and running the executable inside.  However, when I undock and redock, the windows go to my primary monitor (of two attached to the dock) when they were originally on the secondary monitor.  Is the tool unable to place the windows back where they were across multiple monitors?

**Comment by manutalcual** [comment]
Which apps are they? I've seen it has problems handling Microsoft apps, like Outlook, MS Teams, and so. I don't know why and don't have time to fix. For me, reorganizing just two or three windows is not a pain. Before developing this app I needed to reposition a dozen windows, which is really a pain

**Comment by manutalcual** [comment]
It works with three monitors BTW.

**Comment by Ardrikk** [comment]
Outlook, Skype for Business and Slack

**Comment by manutalcual** [comment]
Yep. Just as said: Microsoft products (may be Slack isn't, but I bet it uses some MS thing.) I don't know why, but they tend to have some "unusual" characteristics not compatible with everybody else.
I swear those apps appear somewhat partially in the "reposition" list my app builds but they don't respond to the reposition message.
 Unfortunately, my app doesn't gives me money to pay anything (bills, mortgage, kids university, etc.) so I can't maintain it.

**Comment by Ardrikk** [comment]
Fair enough.  Thanks for the information!
