### ISSUE TITLE
Feature request: Simplify usage or clarify "Use Instructions"

### ISSUE THREAD

**Issue by fresheneesz** [manutalcual/winredock#19]
I don't understand the purpose of separating "Get windows" and "Save config". Why not just have a "Save windows" button that does both?

Also, I don't know what "read config" does. Is it suppose to manually re-position windows?

I would recommend changing these buttons to:

"Save windows" - saves your window positions for later loading (either when displays change or if you press "Load windows").
"Load windows" - manually triggers window repositioning.

**Comment by manutalcual** [comment]
Hello,

Menu options are deprecated. I should remove them as they are useless now, but I don't have time to do it.
I'm going to update all this in coming weeks.

Thanks to take your time to contribute!

**Comment by fresheneesz** [comment]
Np. I've created a pull request clarifying what you just said: https://github.com/manutalcual/winredock/pull/20

**Comment by manutalcual** [comment]
Wow! Thanks a lot! Already merged.
