### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by berot3** [manutalcual/winredock#22]
It would be cool if bin would be released under "Releases": https://github.com/manutalcual/winredock/releases

That why when someone watches your repo, a notification is sent out.
And also it makes sense to download from Releases and not from some bin-folder :)

**Comment by manutalcual** [comment]
Yes. Thank you for your suggestion. I'm going to follow.
I thinks in the next weeks I would be able to put some time on this!

Thanks

**Comment by manutalcual** [comment]
Done!
I'm going to find time to develop this further. Don't know how just know but I'm going to do my best effort.

**Comment by aznan2** [comment]
Crazy. The first I heard of this program was today, and 30 minutes later there was a first release.

Tried it and it worked beautifully. Just wanted to say thanks!

**Comment by manutalcual** [comment]
Hi,

Thanks for your kind words. I hope I have time to make it better!

Kind regards,
Manu

**Comment by manutalcual** [comment]
Where have you heard of this program by the way?

Kind regards,
Manu

**Comment by aznan2** [comment]
This answer: https://superuser.com/a/1510870 to the question "How do I restore windows back to their original screen when re-connecting external monitor?", which is the third google result i get for the query "windows 10 save window layout".
