### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by ksawerykarwacki** [manutalcual/winredock#23]
I unpacked as instruction states but I am unable to start due to two errors:

![image](https://user-images.githubusercontent.com/11694791/76007532-7c6e3680-5f0e-11ea-84e9-3f396e4f221a.png)
![image](https://user-images.githubusercontent.com/11694791/76007554-842ddb00-5f0e-11ea-9869-5b43e2f1815d.png)

**Comment by manutalcual** [comment]
I've created another release [v0.4bf](https://github.com/manutalcual/winredock/tree/v0.4bf) to fix this.
You can download and try.

**Comment by aznan2** [comment]
Can confirm that it works now. Thank you!

**Comment by manutalcual** [comment]
Closing the issue!
