### ISSUE TITLE
I'm not able to run wm.exe because of this error.. I'm not compiling the program, just running the file from bin.

### ISSUE THREAD

**Issue by manutalcual** [manutalcual/winredock#24]
I'm not able to run wm.exe because of this error.. I'm not compiling the program, just running the file from bin.

![Annotation 2020-03-05 123824](https://user-images.githubusercontent.com/4406427/76023671-6e082680-5ede-11ea-82df-0f8a2df87f62.png)

_Originally posted by @sbiefeni in https://github.com/manutalcual/winredock/issues/14#issuecomment-595436099_

**Comment by manutalcual** [comment]
I've created a new issue for this as this is not the same failure, but thanks to point out the failing dlls. I'm going to fix this.

**Comment by manutalcual** [comment]
I've created another [release](https://github.com/manutalcual/winredock/tree/v0.4bf) with the missing DLLs.
Try and if it works I will merge and close the issue.

**Comment by shan-du** [comment]
Hi, I'm still seeing that error message when running the latest **exe** binary :(
And now there's a new error:

![image](https://user-images.githubusercontent.com/4749854/77560437-e174d680-6e93-11ea-9f2f-73ea249e5886.png)

Note: I don't have WSL installed

**System Info:**
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
Processor	Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)
Display	Intel(R) HD Graphics 520

```

P.S. Thanks for making this tool tho! If it works, it will save me so much time!

**Comment by manutalcual** [comment]
Hi,

Release [v0.5rc](https://github.com/manutalcual/winredock/tree/v0.5rc) has the correct binary and DLLs needed to run in Windows.

![imagen](https://user-images.githubusercontent.com/12857333/77620614-053f2780-6f3b-11ea-8977-2524f09ff905.png)

As you can see the following image it has the suposedly missing file. Try downloading again and uncompress it in a folder.

![imagen](https://user-images.githubusercontent.com/12857333/77620534-dd4fc400-6f3a-11ea-86f7-c0ecc24af8c6.png)

Hope this helps,

Manuel

**Comment by shan-du** [comment]
Yeeee, this one works! Thank you so much! 👍 👌
