### ISSUE TITLE
Suspicious IP address contained within wm.exe

### ISSUE THREAD

**Issue by Wilbur-H** [manutalcual/winredock#53]
Dear developer,

Your app, wm.exe, contains an IP address that has been reported on several websites. The IP address in reference is: 20.99.133.109
The associated IP engages in Port Scans, Spam, and Web Application Attacks.

May you kindly verify, please? 

![Screenshot 2024-07-12 161403](https://github.com/user-attachments/assets/dd5ef49f-c7d2-4486-9860-6b08e287b403)
![Screenshot 2024-07-12 161339](https://github.com/user-attachments/assets/84c3319c-9e21-41ba-9653-c4f858bdbd09)
![Screenshot 2024-07-12 161256](https://github.com/user-attachments/assets/7fde45ba-3a43-4990-ac10-5bf2df51e1e6)
![Screenshot 2024-07-12 161224](https://github.com/user-attachments/assets/92775ea4-ab1c-41f8-a053-94cbecfca140)
![Screenshot 2024-07-12 161115](https://github.com/user-attachments/assets/5f4aaeed-0ad2-45a4-bfda-b54708808536)
![Screenshot 2024-07-12 161033](https://github.com/user-attachments/assets/99244b8e-26c6-4812-a28f-7bf2a8d0fb82)
![Screenshot 2024-07-12 161005](https://github.com/user-attachments/assets/10d16e71-fe3d-464c-b8ff-27aac58aa736)

**Comment by manutalcual** [comment]
That IP is registered by Microsoft. My app doesn't have anything related to networking.
There is a wm.exe app running in almost every Windows machine (to my knowledge) that has the very same name.

A whois search will tell you so:
![Screenshot from 2024-07-12 17-01-21](https://github.com/user-attachments/assets/d834a08a-b596-45bc-aa98-957df4f4fa8d)

Some links for that app name:

[File.net](https://www.file.net/process/wm.exe.html)
[processlibrary.com](https://www.processlibrary.com/en/directory/files/wm/24410/)
[auditmypc](https://www.auditmypc.com/wm.asp)
[anti-spy](https://www.anti-spy.info/process/wm.exe.html)
[file inspect](https://www.fileinspect.com/fileinfo/wm-exe/)

You can download the source code here and verify there isn't anything network related.

Thanks for caring for us, users, all users (seriously.)
