### ISSUE TITLE
Window not visible after restoring position

### ISSUE THREAD

**Issue by aronovgj** [manutalcual/winredock#8]
Sometimes, even if a window was not moved it disappears. It seems like it somehow is in foreground but not displayed.

So what I do is this:
1) Restore window positions
2) A window is not visibe
3) Klick on icon of corresponding invisible window in task bar (focus of currently active window of another program disappears)
4) Klick again (focus returns to active window)
5) Klick again (window of initially invisible window is visible again with focus on that window)

That happens often (like every second or third time) but not always with different windows.

I am using Win10 with several desktops.

Also: awesome tool!

**Comment by manutalcual** [comment]
I'll take a loot at that.

Thank you for using and finding it awesome!

**Comment by aronovgj** [comment]
New finding: 
Most of the time this happens with Microsoft products (Outlook and OneNote, never with Excel though until now) but sometimes (every 10th time) it also happens with non-Microsoft products. 
For some programs I saw this happen several times, for some it never occurred (e.g. Notepad++, Explorer, Firefox, Skype)

**Comment by aronovgj** [comment]
Issue does not occur anymore.
